### PR TITLE
Feature/sckan 259

### PR DESCRIPTION
**Pull request by afonsobspinto**
Closes https://metacell.atlassian.net/browse/SCKAN-259 and https://metacell.atlassian.net/browse/SCKAN-253 (only in the frontend, not in the admin page)

- Applies the new state machine transitions as defined here:
https://lucid.app/lucidchart/2d9ff911-1a36-4af4-ad4a-4ee88fb58099/edit?invitationId=inv_9147956b-6d03-4711-b691-706787c27efc&page=3R49srWfLI_t#
(All states V2)

- Adds migration to remove the previous constraints
- Adds migration to change the deprecated states and add new constraints

- Renames statementService to statementStateService (same for sentence).
- Moves compile_journey out of the statement state service.

- Regenerates the API and fixes some type mismatches

- Updated the end to end test (but didn't run it)

### CODE REVIEW

**Comment by afonsobspinto** [comment]
@ddelpiano I left this PR as draft so that we don't have dev change while you are testing the release. Please make the PR ready for review and mark @zsinnema as reviewer when you think it's fine to have this PR merged.

**Comment by zsinnema** [comment]
@afonsobspinto did you test the migrations?

**Comment by afonsobspinto** [comment]
> @afonsobspinto did you test the migrations?

Locally, yes:

```
[☸ docker-desktop][ feature/SCKAN-259][$?⇡][🐍 v3.9.9(sckan)]
sckan-composer/backend ❯ python manage.py makemigrations
Migrations for 'composer':
  composer/migrations/0039_remove_connectivitystatement_state_valid_and_more.py
    - Remove constraint state_valid from model connectivitystatement
    - Remove constraint sentence_state_valid from model sentence
    - Alter field state on exportmetrics
    - Create constraint state_valid on model connectivitystatement
    - Create constraint sentence_state_valid on model sentence

[☸ docker-desktop][ feature/SCKAN-259][$?⇡][🐍 v3.9.9(sckan)]
sckan-composer/backend ❯ python manage.py makemigrations composer --empty
Migrations for 'composer':
  composer/migrations/0040_auto_20240213_1301.py

[☸ docker-desktop][ feature/SCKAN-259][$?⇡][🐍 v3.9.9(sckan)]
sckan-composer/backend ❯ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authtoken, composer, contenttypes, sessions, social_django
Running migrations:
  Applying composer.0036_convert_unknown_to_null... OK
  Applying composer.0037_remove_unknown_enum... OK
  Applying composer.0038_alter_connectivitystatement_circuit_type_and_more... OK
  Applying composer.0039_remove_connectivitystatement_state_valid_and_more... OK
  Applying composer.0040_auto_20240213_1301... OK

```

**Comment by zsinnema** [comment]
@afonsobspinto there are some merge conflicts, can you have a look? thanks

**Pull request merged**
